[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_lock = "DNeSEvYcNVwGYruy756J5C2rDMGuTQ2yFhnTkjRHrwYi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/Users/paritoshkumar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
