[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
token_lock = "GBpt6Vk31WJfh6DsnTRGy585yF4zMLv8QD2TwX3GJQvM"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/paritoshkumar/.config/solana/my-new-wallet.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
