[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
token_lock = "DNeSEvYcNVwGYruy756J5C2rDMGuTQ2yFhnTkjRHrwYi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/paritoshkumar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
